<tr>
    <td class="label"><label for="<?php echo $this->getElement()->getHtmlId()?>"><?php echo $this->getElement()->getLabel()?></label></td>
    <td class="value">
        <input id="<?php echo $this->getElement()->getHtmlId()?>" name="<?php echo $this->getElement()->getHtmlId()?>" value="<?php echo $this->getElement()->getValue()?>" class=" input-text" type="text">
        &nbsp;<a href="https://gls-group.eu/DE/de/depot-paketshop-suche" target="_blank">https://gls-group.eu/DE/de/depot-paketshop-suche</a>
    </td>
</tr>