<script type="text/javascript">
    function JobRequest() {

        this.poll = false;

        this.url = '<?php echo Mage::helper('adminhtml')->getUrl('*/*/ajax') ?>';

        this.activatePoll = function () {
            this.poll = true;
            this.runPoll();
        };

        this.disablePoll = function () {
            clearTimeout(this.poll);
            this.poll = false;
        };

        this.runPoll = function () {
            var self = this;
            var poll = setTimeout(function () {
                var jobIds = [];
                $$('.job-status-column').each(function(elem){
                    jobIds.push(elem.identify().replace('job-',''));
                });
                new Ajax.Request(self.url, {
                    parameters: {'jobIds[]':jobIds},
                    onSuccess : function(transport) {
                        var response = transport.responseJSON || transport.responseText.evalJSON(true) || {};
                        //console.log(response);
                        var noUpdates = 1;
                        if(response.length) {
                            response.each(function (item) {
                                /*if(!$('job-' + item.id)) {
                                    window.location.reload();
                                }*/
                                if(!item.no_updates) {
                                    noUpdates = 0;
                                }
                                $('job-' + item.id).update(item.status);
                                $('job-' + item.id).up().up().select('.job_completed').each(function (item2) {
                                    item2.update(item.completed);
                                });
                                $('job-' + item.id).up().up().select('.job_printed').each(function (item2) {
                                    item2.update(item.printed);
                                });
                                $('job-' + item.id).up().up().select('.job_error_messages').each(function (item2) {
                                    item2.update(item.error_messages);
                                });
                                $('job-' + item.id).up().up().select('.job_action').each(function (item2) {
                                    item2.update(item.action);
                                });
                                $('job-' + item.id).up().up().select('.job_error_items').each(function (item2) {
                                    item2.update(item.error_items);
                                });
                            });
                        }
                        if(noUpdates) {
                            self.disablePoll();
                        } else {
                            self.runPoll();
                        }
                    }
                });
            }, 10000);
        };
    }
    var jobRequest = new JobRequest();
    jobRequest.activatePoll();
</script>